version: "3.9"

services:
  historical-sync:
    build: .
    container_name: historical_sync
    command: python scripts/historical_sync.py
    restart: "no"  # Une seule exécution

  daily-sync:
    build: .
    container_name: daily_sync
    command: python scripts/daily_sync.py
    restart: always  # Boucle infinie